#!/usr/bin/env bash
# This script audits DNS records for specified subdomains of a domain.

function audit_subdomain {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomain=("$subdomain")
    else
        subdomains=("$subdomain")
    fi

    for sub in "$(subdomains[0]}"; do
        record_type=$ (dig "$sub.$domain"  | awk '/ANSWER SECTION/ { getline; print $4 }'}
        destination=$ (dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline ; print $5 }'}
    done
}

audit_subdomain "$1" "$2"
